### ISSUE TITLE
Perhaps a bug

### ISSUE THREAD

**Issue by mstrens** [yaroslavVl/6-AXIS-USBCNC-GRBL#11]
in util/stm32f10x_it.c, there is currently this code

#ifdef USEUSB
/* Includes ------------------------------------------------------------------*/
#include "stm32f10x_it.h"
#include "usb_lib.h"
#include "usb_istr.h"
#include "hw_config.h"

There is no #Endif just after (only at the end).
So this file is not processed if USEUSB is not defined

**Comment by robomechs** [comment]
Don't know. It's "usbcnc" sorce code.
