### ISSUE TITLE
two GRBL welcome message when power is applied

### ISSUE THREAD

**Issue by mstrens** [yaroslavVl/6-AXIS-USBCNC-GRBL#14]
I have implemented NC hard limits (connected to ground).
I put a RC filter to avoid false trigering.
I have configure GRBL for hard limit ($21=1) and invert mask ($5=1)

When I power up the stm32, I get twice the welcome message (Grbl 1.1f ['$' for help]) folowed by an ALARM:1.
I am forced to do a soft reset to go on.

This does not occurs if I do hard reset using the reset button on the blue pill (I get only one welcome message and I do not have to do a softreset.

I check the code and it seems that at power on, I get a false trigering of interrupt on limit pin.

I fixed the issue adding delay of 100msec (perhaps a lower value will be ok) in the init function of the limit (in limit.c).
Here my code.
`
	if (bit_istrue(settings.flags, BITFLAG_HARD_LIMIT_ENABLE))
	{
		delay_ms(100);                                      // added by MS for debug
		GPIO_EXTILineConfig(GPIO_LIMIT_PORT, X_LIMIT_BIT);
		GPIO_EXTILineConfig(GPIO_LIMIT_PORT, Y_LIMIT_BIT);
		GPIO_EXTILineConfig(GPIO_LIMIT_PORT, Z_LIMIT_BIT);
`

**Comment by robomechs** [comment]
Done, but hasn't checked.
