### ISSUE TITLE
Reset not working on Blue Pill and Black Pill with limit alarm is set

### ISSUE THREAD

**Issue by troth530** [yaroslavVl/6-AXIS-USBCNC-GRBL#27]
Hi, I opened a new issue as this is not USB related.  I cannot clear an alarm after hitting a limit switch and after the limit alarm gets set.  I cannot get Ctrl+X to work on blue pill or back pill (STM32f103C8). Reset button does not work either.  $X works for some alarms, but not a limit alarm (with $22=1). 

Shutting down the software host and unplugging the USB does work, but it seems like it should respond to soft reset ($X, Ctrl+X) or a hard reset (button).  It should not require a complete reboot.

Thank you for all your hard work!

**Comment by creisey** [comment]
how did you compile the firmware for blackpill?

**Comment by robomechs** [comment]
#12
