### ISSUE TITLE
Using USART instead of USB (#undef USEUSB)

### ISSUE THREAD

**Issue by Lenrockus** [yaroslavVl/6-AXIS-USBCNC-GRBL#3]
Во первых, хочу поблагодарить за проделанный труд, очень кстати , но возникла проблема с включение UART. добавление #undef USEUSB в main.c отключает юсб но не включает uart. Можете проверить?

**Comment by Lenrockus** [comment]
второй способ (с удалением useusb) работает

**Comment by robomechs** [comment]
You ask: "Adding #undef USEUSB into main.c turns off USB, but doesn't turn on UART. The second way (delete USEUSB from symbols) works".
Yes. I'm wrong. You have to add #undef USEUSB in grbl.h after #ifdef STM32F103C8.
