### ISSUE TITLE
Another way to upload

### ISSUE THREAD

**Issue by matthew73210** [yaroslavVl/6-AXIS-USBCNC-GRBL#5]
Just some info that you can add to the wiki.

With Atollic you can ask it to output a .bin or .hex.
Once you have one of these files you can upload them with this program : "https://www.st.com/content/st_com/en/products/development-tools/software-development-tools/stm32-software-development-tools/stm32-programmers/flasher-stm32.html?"
You just have to set the boot pins first.

On another note in Atollic you can set the flash to 128KB which seems to be the right flash size for my bluepill.

**Comment by Alfrederson** [comment]
I can confirm this works. I don't know if chips like CP2102 and CH340 actually drop the connection, but if someone designs a custom board with this chip and the a usb-serial chip (not really needed, in my opinion), it would be a nice feature to include a switch to toggle the state of the Boot0 pin: in one mode the board boots up the program normally, in another mode it runs the serial bootloader.
