### ISSUE TITLE
Hello, is there any tutorial on how to import to atollic, compile and download to bluepill ??

### ISSUE THREAD

**Issue by sinfocomp** [yaroslavVl/6-AXIS-USBCNC-GRBL#6]

**Comment by matthew73210** [comment]
Download it 
Once Atollic is up import a project
Find the grbl and config.h files
Change options as you wish, but don't change board options in these two config files
Go to options and select debut output (choses what you want : .hex .bin ...)
Compile 
Then it is up to you how you upload it, i use flash demonstrator from stm which i liked in the other issue i posted.

If you need specifics i can help:
Have you got Atollic up and running ?

**Comment by robomechs** [comment]
See "Get started" section https://github.com/yaroslavVl/6-AXIS-USBCNC-GRBL#get-started
You don't need to import, just open it.
If you want fast result (if you want to try it), you can program your board (bluepill) with <b>stm32grbl11.hex</b> from "Debug" folder (without compilation). You can do this with Atollic or <b>STM32 ST-LINK Utility</b>. But you must have a <b>programmer</b>. You can also program it through the UART, but this a bit difficult and you will need a USB-UART adapter (see https://github.com/yaroslavVl/6-AXIS-USBCNC-GRBL/issues/5 ).
